
theme: minima   # or minima / minimal-mistakes / other theme

email: 2026 Vivek Singh Ph.D.
description: Personal academic website

sass:
  style: compressed


navigation:
  - title: Home
    url: /
  - title: About
    url: /about/
  - title: Research
    url: /research/
  - title: Publications
    url: /publications/
